### ISSUE TITLE
Kippo- Graph install error

### ISSUE THREAD

**Issue by maracas12** [mercolino/mhn_kippo_graphs#1]
Hi I am having an issue with my install  -

ubuntu@ip-172-31-16-111:/opt/mhn/scripts/mhn_kippo_graphs$ sudo sh install_kippo_graph.sh
- sudo apt-get update
  Ign http://security.ubuntu.com trusty-security InRelease
  Ign http://ppa.launchpad.net trusty InRelease
  Hit http://ppa.launchpad.net trusty Release.gpg
  Hit http://ppa.launchpad.net trusty Release
  Hit http://ppa.launchpad.net trusty/main amd64 Packages
  Hit http://security.ubuntu.com trusty-security Release.gpg
  Hit http://ppa.launchpad.net trusty/main Translation-en
  Ign http://downloads-distro.mongodb.org dist InRelease
  Hit http://security.ubuntu.com trusty-security Release
  Ign http://eu-west-1.ec2.archive.ubuntu.com trusty InRelease
  Hit http://security.ubuntu.com trusty-security/main Sources
  Ign http://eu-west-1.ec2.archive.ubuntu.com trusty-updates InRelease
  Hit http://downloads-distro.mongodb.org dist Release.gpg
  Hit http://security.ubuntu.com trusty-security/universe Sources
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty Release.gpg
  Hit http://security.ubuntu.com trusty-security/main amd64 Packages
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates Release.gpg
  Hit http://downloads-distro.mongodb.org dist Release
  Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty Release
  Hit http://security.ubuntu.com trusty-security/main Translation-en
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates Release
  Hit http://security.ubuntu.com trusty-security/universe Translation-en
  Hit http://downloads-distro.mongodb.org dist/10gen amd64 Packages
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/main Sources
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/universe Sources
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/main amd64 Packages
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/universe amd64 Packages
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/main Translation-en
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty/universe Translation-en
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/main Sources
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/universe Sources
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packages
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/main Translation-en
  Hit http://eu-west-1.ec2.archive.ubuntu.com trusty-updates/universe Translation-en
  Ign http://eu-west-1.ec2.archive.ubuntu.com trusty/main Translation-en_US
  Ign http://eu-west-1.ec2.archive.ubuntu.com trusty/universe Translation-en_US
  Ign http://downloads-distro.mongodb.org dist/10gen Translation-en_US
  Ign http://downloads-distro.mongodb.org dist/10gen Translation-en
  Reading package lists... Done
- sudo apt-get install -y mysql-server libpng12-dev libfreetype6-dev libxft-dev
  Reading package lists... Done
  Building dependency tree
  Reading state information... Done
  libpng12-dev is already the newest version.
  libxft-dev is already the newest version.
  libfreetype6-dev is already the newest version.
  mysql-server is already the newest version.
  0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
- sed -i s/127.0.0.1/0.0.0.0/g /etc/mysql/my.cnf
- sudo service mysql restart
  mysql stop/waiting
  mysql start/running, process 17035
- dirname install_kippo_graph.sh
- MHN_HOME=./../..
- cd ./../..
- pwd
- MHN_HOME=/opt/mhn
- . env/bin/activate
- deactivate nondestructive
- unset pydoc
- [ -n  ]
- [ -n  ]
- [ -n  -o -n  ]
- [ -n  ]
- unset VIRTUAL_ENV
- [ ! nondestructive = nondestructive ]
- VIRTUAL_ENV=/opt/mhn/env
- export VIRTUAL_ENV
- _OLD_VIRTUAL_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- PATH=/opt/mhn/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- export PATH
- [ -n  ]
- [ -z  ]
- _OLD_VIRTUAL_PS1=#
- [ x != x ]
- basename /opt/mhn/env
- [ env = __ ]
- basename /opt/mhn/env
- PS1=(env)#
- export PS1
- alias pydoc=python -m pydoc
- [ -n  -o -n  ]
- pip install pymysql numpy matplotlib PILLOW
  The directory '/home/ubuntu/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
  The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
  The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
  Collecting pymysql
  Downloading PyMySQL-0.6.6-py2.py3-none-any.whl (66kB)
    100% |################################| 69kB 1.5MB/s
  Collecting numpy
  Downloading numpy-1.9.2.tar.gz (4.0MB)
    100% |################################| 4.0MB 143kB/s
    Running from numpy source directory.
  Collecting matplotlib
  Downloading matplotlib-1.4.3.tar.gz (50.4MB)
    99% |############################### | 50.4MB 30.6MB/s eta 0:00:01  Exception:
  Traceback (most recent call last):
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 355, in prepare_files
      do_download, session=self.session,
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/download.py", line 782, in unpack_url
      session,
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/download.py", line 667, in unpack_http_url
      from_path, content_type = _download_http_url(link, session, temp_dir)
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/download.py", line 843, in _download_http_url
      _download_url(resp, link, content_file)
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/download.py", line 615, in _download_url
      for chunk in progress_indicator(resp_read(4096), 4096):
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/utils/ui.py", line 46, in iter
      for x in it:
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/download.py", line 580, in resp_read
      decode_content=False):
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 256, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 186, in read
      data = self._fp.read(amt)
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
      self.__callback(self.__buf.getvalue())
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 205, in cache_response
      self.serializer.dumps(request, response, body=body),
    File "/opt/mhn/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 80, in dumps
      data, separators=(",", ":"), sort_keys=True,
    File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
      sort_keys=sort_keys, **kw).encode(obj)
    File "/usr/lib/python2.7/json/encoder.py", line 210, in encode
      return ''.join(chunks)
  MemoryError

**Comment by mercolino** [comment]
I made some tests with a Virtual Machine, and I had problems installing the add-on with low ram memory, I run the test with 1 Gb of Ram and int runs perfectly, obviously it will depend and how loaded is your server, my recommendation is to increase the RAM.
