### ISSUE TITLE
Update MySQL Databases after Kippo Sensor Deployment Error

### ISSUE THREAD

**Issue by maracas12** [mercolino/mhn_kippo_graphs#2]
Update MySQL Databases after Kippo Sensor Deployment

 Command - 
sudo /opt/mhn/env/bin/python /opt/mhn/scripts/mhn_kippo_graphs/kippo_update_mysql.py

This doesnt seem to work correctly can you confirm it is correct

**Comment by mercolino** [comment]
The command is correct, you should have at least one kippo sensor with mysql support, in order the command to work.

**Comment by maracas12** [comment]
I am getting the following error  - -

ubuntu@ip-172-31-19-19:/opt/mhn/scripts/mhn_kippo_graphs$ sudo /opt/mhn/env/bin/python /opt/mhn/scripts/mhn_kippo_graphs/kippo_update_mysql.py
Traceback (most recent call last):
  File "/opt/mhn/scripts/mhn_kippo_graphs/kippo_update_mysql.py", line 5, in <module>
    import pymysql
ImportError: No module named pymysql
ubuntu@ip-172-31-19-19:/opt/mhn/scripts/mhn_kippo_graphs$

**Comment by mercolino** [comment]
The library pymysql is missing, the install script ran smoothly? because the library is installed by the script in the virtual environment.

**Comment by maracas12** [comment]
Uggh I am totally lost. I have spent hours doing this. Thanks for your help so far. 

I am trying this on an EC2 instance should this be a problem 

Wickh is the correct version of pymysql to install cause there must be an error somewhere

**Comment by mercolino** [comment]
Tomorrow I will release a video showing the installation process. The installation process is very easy if you follow all the steps. There should be no problem y doing this on an EC2 instance, you should install pymysql in the virtual environment of MHN if not it does not work, if pymysql was not installed then for sure there will be another problems in the installation, wait for the video tomorrow and follow it.

**Comment by mercolino** [comment]
Hi, as promised here it is the video: http://youtu.be/fbs4U2Yf55g

Regards  
Miguel
