### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by JonathanPhillips** [mercolino/mhn_kippo_graphs#3]
I went through the installation of mhn_kippo_graphs and when I tried logging back into MHN, the login page wasn't loading. I rebooted my server and tried logging into the webpage and got an internal server error. I am checking different services, everything appears to be running except when I run sudo supervisorctl status, I get:

mhn-celery-beat                  FATAL      Exited too quickly (process log may have details)
mhn-celery-worker                FATAL      Exited too quickly (process log may have details)

Any ideas??

I'm running Ubuntu 12.04

**Comment by mercolino** [comment]
Hi Jonathan, i just installed a fresh mhn server on an Ubuntu server 14.04 and kippo graph for mhn and everything went well, It should be no difference with Ubuntu 12.04, if you are having trouble with celery, then it should be some problem with the mhn installation, try to look on the processes logs to see which errors are you having, you could see where the log files are located by looking at the supervisor service configuration file on /etc/supervisor/conf.d/<service>.

If you found nothing on the servers then try the following:
- Edit the file: /opt/mhn/server/mhn.py
- Change the variable debug from False to True
- Run mhn.py with the command: /opt/mhn/env/bin/python /opt/mhn/server/mhn.py
- connect to your server ip port 8000, if there is any error on the code you should see it on the console of the server, and maybe on the webpage.
- Remember to change everything back to normal to not expose any info to the public if you are running this on a production environment.

Regards
Miguel

**Comment by JonathanPhillips** [comment]
Hi Miguel,
Just wanted to update you.  I ended up reinstalling a fresh MHN server just b/c that was going to be much faster than trying to troubleshoot the previous issues. I appreciate your response.

**Comment by mercolino** [comment]
Glad it worked.....
